name: CI - (base)
env:
  MIDNIGHTCI_PACKAGES_WRITE: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      workspace:
        type: string
        description: The workspace folder that should be the target of the workflow.
        required: true
      node-version-file:
        type: string
        required: false
        default: '.nvmrc' # Default to the Node.js version defined in the repo root.
      coverage-files:
        type: string
        required: false
        default: ''
      create-package-artifacts:
        type: boolean
        description: A flag indicating whether the compiled packages should be created and attached to the build.
        required: false
        default: false

jobs:
  ci:
    name: Build, Lint and Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./${{ inputs.workspace }} # Workspace name has affinity to a folder in the root of the repo.
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # ratchet:actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Load environment variables
        run: |
          export $(grep -v '^#' .github/env/global.env | xargs)
          for var in $(cut -d= -f1 .github/env/global.env); do
            echo "$var=${!var}" >> $GITHUB_ENV
          done

      - name: Log in to GitHub Container registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # ratchet:docker/login-action@v4.2.0
        with:
          registry: 'https://ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v4
        with:
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@midnight-ntwrk'
          node-version-file: ${{ inputs.node-version-file }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}
      - name: Configure yarn
        run: |
          yarn config set 'npmScopes.midnight-ntwrk.npmAuthToken' "$MIDNIGHTCI_PACKAGES_WRITE"
          yarn config set 'npmRegistries["https://npm.pkg.github.com"].npmAuthToken' "$MIDNIGHTCI_PACKAGES_WRITE"
          yarn config set 'npmRegistries["https://npm.pkg.github.com"].npmAlwaysAuth' true
      - name: Cache Turbo and Yarn dependencies
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: |
            **/node_modules
            ~/.yarn
            .turbo
          key: turbo-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/turbo.json') }}
          restore-keys: |
            turbo-${{ runner.os }}-

      - name: Install dependencies
        run: |
          yarn install

      - name: Run build
        run: yarn build --cache-dir ./turbo
        env:
          GITHUB_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: |
          yarn test --concurrency 1 --cache-dir ./turbo
        env:
          GITHUB_TOKEN: ${{ secrets.MIDNIGHTCI_PACKAGES_WRITE }}

      - name: Aggregate coverage reports
        run: |
          mkdir -p .nyc_output
          find . -type f -name 'coverage-final.json' -exec cp {} .nyc_output/ \;
          npx --yes nyc merge .nyc_output coverage.json
          npx --yes nyc report --reporter=html --report-dir=coverage --temp-dir=.nyc_output
          rm -rf .nyc_output

      - name: Merge report as ZIP
        run: |
          #ArtiomTr/jest-coverage-report-action@v2 has a bug, this is temp solution
          mv coverage coverage_$(date +"%Y%m%d%H%M%S")
          zip -r coverage-${{ inputs.workspace }}.zip coverage*

      - name: Upload Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # ratchet:actions/upload-artifact@v4
        with:
          name: Coverage Report ${{ inputs.workspace }}
          path: ${{ inputs.workspace }}/coverage-${{ inputs.workspace }}.zip

      - name: Publish Test Coverage
        if: ${{ inputs.coverage-files }} # Publish the comment if we have received coverage files
        uses: MishaKav/jest-coverage-comment@40d7aed38d0fbaea266c34c12ab06356eec894eb # ratchet:MishaKav/jest-coverage-comment@v1
        with:
          hide-comment: false
          unique-id-for-comment: ${{ inputs.workspace }}-coverage
          multiple-files: ${{ inputs.coverage-files }}

      - name: Pack and Upload Package Artifacts
        if: ${{ inputs.create-package-artifacts }}
        uses: ./.github/actions/create-package-artifacts
        with:
          package-archive-name: ${{ inputs.workspace }}
          working-directory: ./${{ inputs.workspace }}
